### ISSUE TITLE
Todo List week

### ISSUE THREAD

**Issue by Moufid17** [Moufid17/Snake#3]
### Todo
- [x]  Basic Laravel Auth: ability to log in as administrator
- [ ] Use database seeds to create first user with email admin@admin.com and password “password”
- [ ] Use basic Laravel resource controllers with default methods – index, create, store etc.
